name: Push to Main
on:
  push:
    branches:
      - main
  
jobs:
  docker_build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.docker_user }}
          password: ${{ secrets.docker_pass }}
      - name: Build docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          load: true
          push: false
          tags: ${{ vars.docker_user }}/solar-system:${{ github.sha }}
      - name: Aqua Security Trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ vars.docker_user }}/solar-system:${{ github.sha }}'
          format: 'table'
          output: trivy-results.sarif
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: Aqua Trivy report
          path: trivy-results.sarif
      - name: Docker push
        run: docker push ${{ vars.docker_user }}/solar-system:${{ github.sha }}